### ISSUE TITLE
Spaces in file names

### ISSUE THREAD

**Issue by Weltraumschaf** [joelparkerhenderson/architecture_decision_record#15]
You should not recommend using spaces in file names. It is better to only allow non-whitespace ASCII characters. That will make life more easier when doing scripted stuff because there are lot of tools which does not escape paths correctly.

**Comment by joelparkerhenderson** [comment]
Can you provide a few examples of tools that do not escape paths correctly, and that's not a bug in the tool?

**Comment by Weltraumschaf** [comment]
Really? You need examples for that? But, ok leave it closed. Every junior developer learns that
 the hard way in the early years...
