### ISSUE TITLE
Typo in repo description.

### ISSUE THREAD

**Issue by skawaguchi** [joelparkerhenderson/architecture_decision_record#29]
Hey @joelparkerhenderson, just noticed this typo:
> Architecture decision record (ADR) examples for software planning, IT leadership, and template documenation

documenation > documentation 

BTW, I've been linking people to your repo for awhile now because it's the best collection of ADR knowledge. Keep up the good work!

**Comment by joelparkerhenderson** [comment]
Thank you - great catch! And I appreciate the linking because good decision records can help so many teams!
