### ISSUE TITLE
Document decision on date format

### ISSUE THREAD

**Issue by koppor** [joelparkerhenderson/architecture_decision_record#5]
Please document the decision, why you chose YYYYMMDD for date format and not YYYY-MM-DD. I know that YYYYMMDD is "allowed by the standard, but is hard to read as a date at first glance".

I would prefer the dashed version, because it clearly separates year from month and month from day.

See also https://xkcd.com/1179/ (https://www.explainxkcd.com/wiki/index.php/1179:_ISO_8601, http://forums.xkcd.com/viewtopic.php?t=100553)

**Comment by joelparkerhenderson** [comment]
Your way is better. I'll change the repo now. Thank you for writing about this! -Joel
